version: '3.3'
services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
  akira-api:
    build: .
    volumes: 
      - .:/code
    env_file: 
       - .env
       - .env.postgres
    depends_on: 
      - db
    links: 
      - db