FROM node:12-alpine

RUN mkdir /code
RUN chown node /code

USER node

WORKDIR /code

COPY --chown=node:node package.json yarn.lock ./

RUN yarn global add @nestjs/cli
RUN yarn install --frozen-lockfile --production

COPY --chown=node:node . ./

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start:prod"]