version: '3.3'
services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
  akira-api:
    image: seitmagambet/akira-api
    volumes: 
      - .:/code
    env_file: 
       - .env
       - .env.postgres
    environment: 
      NODE_ENV: production
    depends_on: 
      - db
    links: 
      - db
    ports:
      - 8000:8000