name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-n-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate firebase-service-account.json
        run: |
          cat <<EOF > firebase-service-account.json
          ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          EOF
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_USERNAME}}/akira-api:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
