name: Deploy
on:
  push:
    branches: [master]
jobs:
  build-n-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Chckout
        uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPOSITORY }}
          dockerfile: akira-api/Dockerfile
          tags: latest
